# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Palm-KeyRing
version:      0.01
version_from: lib/Palm/KeyRing.pm
installdirs:  site
requires:
    Crypt::DES:                    0
    PDA::Pilot:                    0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30
